apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-rabbit
spec:
  selector:
    matchLabels:
      app: orion-rabbit
  replicas: 1
  template:
    metadata:
      labels:
        app: orion-rabbit
    spec:
      containers:
      - name: orion-rabbit
        imagePullPolicy: Always
        image: rabbitmq:3-management
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 15672
        - name: amqp
          containerPort: 5672
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: orion-rabbit
spec:
 type: NodePort
 ports:
  - name: http
    protocol: TCP
    targetPort: 15672
    port: 15672
    nodePort: 32501
  - name: amqp
    protocol: TCP
    targetPort: 5672
    port: 5672
 selector:
  app: orion-rabbit
