apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-registry
  labels:
    app: orion-registry
spec:
  selector:
    matchLabels:
      app: orion-registry
  template:
    metadata:
      labels:
        app: orion-registry
    spec:
      containers:
      - name: orion-registry
        image: anbadrin/orion-project3:registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: orion-registry
  labels:
    app: orion-registry
spec:
  selector:
    app: orion-registry
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091